### ISSUE TITLE
[BUG] rule-java-docs missing method on IDN class

### ISSUE THREAD

**Issue by kevin-gorton-sp** [sailpoint-oss/rule-development-kit#13]
**Describe the bug**
In tha Java Docs located here
https://developer.sailpoint.com/rule-java-docs/sailpoint/server/IdnRuleUtil.html#findAccountsByAttribute-java.lang.String-java.lang.String-java.lang.String-java.lang.Object-

shows the findAccountsByAttribute method defined as 
java.util.List<[Account](https://developer.sailpoint.com/rule-java-docs/sailpoint/rule/Account.html)> findAccountsByAttribute(java.lang.String applicationName, java.lang.String identityName, java.lang.String attributeName, java.lang.Object attributeValue)

but the RDK, or more precisely v1.0 of the rule-java-docs JAR,  is missing this method.

**To Reproduce**
1. Create any rule with the idn class mocked
2. try and add the idn.findAccountsByAttribute("","","","") method
3. See error ( The method findAccountsByAttribute(String, String, String, Object) is undefined for the type IdnRuleUtilJava(67108964)) 

**Expected behavior**
the method would be defined and useable.

**Screenshots**
![image](https://github.com/sailpoint-oss/rule-development-kit/assets/108945538/3d0475cd-e2d1-43bd-be74-32d901379511)
![image](https://github.com/sailpoint-oss/rule-development-kit/assets/108945538/1909e2d6-59c5-4a5e-8943-bf9df7f27061)

**Operating System (please complete the following information):**
 - OS: Windows 11
 - Environment: VSCode
 - main branch pulled 5/13/2024

** Additional Information ** 
this also produces the error when trying to test code with the method.

> java.lang.Error: Unresolved compilation problem:  The method findAccountsByAttribute(any(), any(), any(), any()) is undefined for the type IdnRuleUtil

**Comment by ed-sailpoint** [comment]
Hi team, any indication when this could be addressed? I'm having the same issue, however with `getFirstAccountNativeIdentityByAttribute` method which also seems to be a recent new addition.
Any workaround in the meantime?
