### ISSUE TITLE
[BUG] Include various sailpoint.connector classes in the RDK

### ISSUE THREAD

**Issue by drosenbauer** [sailpoint-oss/rule-development-kit#2]
One of the example rules is as follows:

     import sailpoint.connector.DelimitedFileConnector;

     Map map = DelimitedFileConnector.defaultBuildMap( cols, record );
     String access = (String) map.get( "access" );
     String permission = (String) map.get( "permission" );

    log.debug("Map log: " + map);

     if ( access != null && permission != null ) {
          map.remove("access");
          map.remove("permission");
          map.put("access", access + " - " + permission);
     }
     return map;

This will not currently run in the RDK and so cannot be tested, because `sailpoint.connector.DelimitedFileConnector` is not in the RDK codebase. Of course, developers can copy the connector bundles from their VA and do it that way, but it would be nice if these very common connector classes would be included.

**Comment by tyler-mairose-sp** [comment]
Hey @drosenbauer, this is actually a bug. I included the DelimitedFileConnector in the rules jar so if it's not working for you I must have something cached where it's included. I'll look into this as soon as I can and get a fix in there.

**Comment by tyler-mairose-sp** [comment]
Just got the fix in for this with the following commit! https://github.com/sailpoint-oss/rule-development-kit/commit/de0e3dd447497535eee2cc6719e66ec7252c4351
